// Real REST + SQLite + LangGraph browser check against an explicitly offline
// temporary-database preview, never a real model endpoint.
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { chromium } = require("playwright");

async function main() {
  const base = process.env.KDS_TEAM_UI_URL;
  if (!base) throw new Error("Set KDS_TEAM_UI_URL to an explicitly offline, temporary-database team preview.");
  const browser = await chromium.launch({ headless: true,
    ...(process.env.KDS_TEST_CHROMIUM ? { executablePath: process.env.KDS_TEST_CHROMIUM } : {}) });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
    const errors = [], writes = [];
    page.on("pageerror", e => errors.push(e.message));
    page.on("request", request => { if (["POST", "PUT", "DELETE"].includes(request.method())) writes.push(request.url()); });
    await page.goto(base + "/teams"); await page.waitForLoadState("networkidle");
    const presets = await (await page.request.get(base + "/api/team-presets")).json();
    assert.equal(presets.roles.length, 9); assert.equal(presets.teams.length, 4);
    assert(presets.tools.every(t => !t.name.startsWith("kds_")));
    assert.equal(await page.locator('.role-card[data-preset-role]').count(), 9);
    assert.equal(await page.locator('[data-action="role-presets"]').count(), 0);
    assert.equal(writes.length, 0, "opening the role library does not create records");
    const paperCard = page.locator('[data-preset-role]').first(), roleRef = await paperCard.locator('[data-role-edit]').getAttribute("data-role-edit");
    const roleResponse = roleRef.startsWith("preset:") ? page.waitForResponse(r => r.request().method() === "POST" && r.url().includes("/api/team-presets/roles/")) : null;
    await paperCard.locator('[data-role-edit]').click();
    const paperRole = roleResponse ? await (await roleResponse).json() : (await (await page.request.get(base + "/api/roles")).json()).find(r => r.id === roleRef);
    assert.equal(await paperCard.locator("p").textContent(), paperRole.description);
    assert.equal(await paperCard.locator("p").getAttribute("title"), paperRole.system_prompt);
    assert.equal(await page.locator('input[name="tools"][type="checkbox"]').count(), presets.tools.length);
    assert.equal(await page.locator('input[name="single_max_tokens"]').inputValue(), "");
    await page.locator("#tools-all").check();
    const versionResponse = page.waitForResponse(r => r.request().method() === "POST" && r.url().includes(`/api/roles/${paperRole.id}/versions`));
    await page.locator("#dialog-submit").click();
    const updatedRole = await (await versionResponse).json();
    assert.equal(updatedRole.default_budget.single_max_tokens, null);
    assert.deepEqual(updatedRole.tools.sort(), presets.tools.map(t => t.name).sort());
    assert.deepEqual(updatedRole.sources, paperRole.sources);
    assert.equal(updatedRole.description, paperRole.description);
    await page.waitForFunction(() => !document.querySelector("#dialog-form"));
    await page.locator(`[data-role-equivalence="${updatedRole.equivalence_key}"] [data-role-add]`).click();
    const draftBeforePreview = await page.evaluate(() => localStorage.getItem("kds-team-draft-v1")), writesBeforePreview = writes.length;
    await page.locator('[data-action="team-presets"]').click();
    assert.equal(await page.locator(".preset-card").count(), 4);
    if (process.env.KDS_TEAM_UI_SCREENSHOTS) {
      fs.mkdirSync(process.env.KDS_TEAM_UI_SCREENSHOTS, { recursive: true });
      await page.screenshot({ path: path.join(process.env.KDS_TEAM_UI_SCREENSHOTS, "team-presets.png"), fullPage: true });
    }
    await page.locator('[data-preset-preview]').first().click();
    await page.locator('#preview-topology [data-preview-node]').first().waitFor();
    assert.equal(writes.length, writesBeforePreview);
    assert.equal(await page.evaluate(() => localStorage.getItem("kds-team-draft-v1")), draftBeforePreview);
    assert(await page.locator('#preview-node-details .preview-prompt pre').first().textContent());
    if (process.env.KDS_TEAM_UI_SCREENSHOTS) await page.screenshot({ path: path.join(process.env.KDS_TEAM_UI_SCREENSHOTS, "team-readonly-preview.png"), fullPage: true });
    const teamResponse = page.waitForResponse(r => r.request().method() === "POST" && /\/api\/team-presets\/teams\/[^/]+$/.test(new URL(r.url()).pathname));
    await page.locator('#preview-use').click();
    const paperTeam = await (await teamResponse).json();
    await page.locator("#graph-nodes .graph-node").nth(paperTeam.nodes.length - 1).waitFor();
    assert.equal(await page.locator("#graph-nodes .graph-node").count(), paperTeam.nodes.length);
    assert(await page.locator("#inspector .preset-sources a").count() > 0);
    if (process.env.KDS_TEAM_UI_SCREENSHOTS) await page.screenshot({ path: path.join(process.env.KDS_TEAM_UI_SCREENSHOTS, "team-paper-editor.png"), fullPage: true });
    await page.locator('[data-action="start"]').click();
    assert.equal(await page.locator('input[name="single_max_tokens"]').inputValue(), "");
    assert.equal(Number(await page.locator('input[name="total_max_tokens"]').inputValue()), paperTeam.limits.total_max_tokens);
    assert.equal(Number(await page.locator('input[name="summary_max_tokens"]').inputValue()), paperTeam.limits.summary_max_tokens ?? 1024);
    await page.locator('[data-dialog-close]').first().click();
    await page.locator('[data-action="team-presets"]').click();
    await page.locator("#basic-example").click();
    await page.locator('#preview-use').click();
    await page.locator("#graph-nodes .graph-node").nth(3).waitFor();
    assert((await page.locator("#validation").textContent()).includes("1 个群聊"));
    await page.locator("#whiteboard-enabled").check();
    await page.locator("#whiteboard-format").selectOption("html");
    await page.locator("[data-whiteboard-editor]").first().check();
    await page.locator('[data-action="save"]').click();
    await page.waitForFunction(() => document.querySelector("#save-state").textContent.includes("已保存"));
    const writesBeforeSavedPreview = writes.length, savedDraftBeforePreview = await page.evaluate(() => localStorage.getItem("kds-team-draft-v1"));
    await page.locator('[data-action="team-preview"]').click();
    await page.locator('#preview-topology [data-preview-node]').first().waitFor();
    assert.equal(await page.locator('#preview-topology [data-preview-node]').count(), 4);
    assert.equal(await page.locator('#preview-version').inputValue(), "1");
    assert.equal(writes.length, writesBeforeSavedPreview);
    assert.equal(await page.evaluate(() => localStorage.getItem("kds-team-draft-v1")), savedDraftBeforePreview);
    if (process.env.KDS_TEAM_UI_SCREENSHOTS) await page.screenshot({ path: path.join(process.env.KDS_TEAM_UI_SCREENSHOTS, "team-saved-preview.png"), fullPage: true });
    await page.locator('[data-dialog-close]').first().click();
    if (process.env.KDS_TEAM_UI_SCREENSHOTS) {
      fs.mkdirSync(process.env.KDS_TEAM_UI_SCREENSHOTS, { recursive: true });
      await page.screenshot({ path: path.join(process.env.KDS_TEAM_UI_SCREENSHOTS, "team-editor.png"), fullPage: true });
    }
    await page.locator('[data-action="start"]').click();
    await page.locator('textarea[name="goal"]').fill("真实服务离线验收：父子递归委派、群聊与正式结果");
    await page.locator('input[name="max_concurrency"]').fill("1");
    await page.locator("#dialog-submit").click();
    await page.locator("#run-topology").waitFor();
    await page.locator("#run-status .status-paused").waitFor({ timeout: 20000 });
    const runId = new URL(page.url()).hash.split("/").pop();
    let snapshot = await (await page.request.get(base + "/api/team-runs/" + runId)).json();
    assert.equal(snapshot.agents.length, 4);
    assert.equal(snapshot.tasks.length, 4);
    assert(snapshot.tasks.every(t => t.status === "succeeded"));
    assert.equal(snapshot.definition.whiteboard_enabled, true);
    assert.equal(snapshot.definition.whiteboard_format, "html");
    assert.equal(snapshot.definition.whiteboard_editors.length, 1);
    assert.equal(snapshot.limits.single_max_tokens, null);
    assert(snapshot.usage.completion_tokens > 0);
    assert((await page.locator("#view-content").textContent()).includes(snapshot.usage.completion_tokens.toLocaleString("zh-CN")));
    await page.locator('.observer-nav [data-view="tasks"]').click();
    assert.equal(await page.locator(".task-card").count(), 4);
    const leader = snapshot.agents.find(a => !a.parent_instance_id);
    const frozenName = snapshot.definition.name;
    await page.locator('[data-action="edit-running"]').click();
    await page.locator("#team-name").fill(frozenName + "下一版");
    await page.locator("#team-name").press("Tab");
    await page.locator('[data-action="save"]').click();
    await page.waitForFunction(() => document.querySelector("#save-state").textContent.includes("v2"));
    snapshot = await (await page.request.get(base + "/api/team-runs/" + runId)).json();
    assert.equal(snapshot.definition.name, frozenName, "editing configuration must not change a running snapshot");
    assert.equal(snapshot.team_version, 1);
    await page.goto(base + "/teams#/run/" + runId);
    await page.locator("#run-topology").waitFor();
    const writesBeforeHistoryPreview = writes.length;
    await page.locator('[data-action="runs"]').first().click();
    await page.locator(`[data-run-preview="${runId}"]`).click();
    await page.locator('#preview-topology [data-preview-node]').first().waitFor();
    assert.equal(await page.locator('#preview-topology [data-preview-node]').count(), 4);
    assert.equal(writes.length, writesBeforeHistoryPreview, "frozen run preview does not activate model work");
    if (process.env.KDS_TEAM_UI_SCREENSHOTS) await page.screenshot({ path: path.join(process.env.KDS_TEAM_UI_SCREENSHOTS, "team-history-preview.png"), fullPage: true });
    await page.locator('[data-dialog-close]').first().click();
    await page.locator(`.observer-nav [data-view="agent"][data-view-id="${leader.id}"]`).click();
    await page.locator("#message-form textarea").fill("补充验收条件：记录应保留，但不能重开已交付任务。");
    await page.locator("#message-form button").click();
    await page.locator(".message.human .queued-label").waitFor();
    snapshot = await (await page.request.get(base + "/api/team-runs/" + runId)).json();
    assert.equal(snapshot.tasks.length, 4);
    assert(snapshot.tasks.every(t => t.status === "succeeded"));
    await page.locator('.observer-nav [data-view="room"]').click();
    await page.locator("#message-form textarea").fill("请用一次有限讨论核对上述结论。");
    await page.locator("#message-form button").click();
    await page.waitForFunction(() => [...document.querySelectorAll(".message.human")].some(e => e.textContent.includes("有限讨论")));
    await page.locator('[data-action="resume"]').click();
    await page.waitForTimeout(1800);
    snapshot = await (await page.request.get(base + "/api/team-runs/" + runId)).json();
    assert(snapshot.tasks.length > 4 && snapshot.tasks.length <= 10, "room discussion must remain bounded");
    await page.locator('.observer-nav [data-view="system"]').click();
    await page.locator('[data-auxiliary="score"]').click();
    await page.locator('textarea[name="topic"]').fill("核对团队当前讨论参与意愿");
    await page.locator("#dialog-submit").click();
    await page.waitForFunction(() => !document.querySelector("#dialog-form"));
    await page.waitForFunction(() => document.querySelector("#view-content").textContent.includes('"score": 50'));
    await page.locator('.observer-nav [data-view="overview"]').click();
    if (process.env.KDS_TEAM_UI_SCREENSHOTS) await page.screenshot({ path: path.join(process.env.KDS_TEAM_UI_SCREENSHOTS, "team-observer.png"), fullPage: true });
    await page.locator('[data-action="finalize"]').click();
    await page.locator("#dialog-submit").click();
    await page.locator("#run-status .status-completed").waitFor();
    snapshot = await (await page.request.get(base + "/api/team-runs/" + runId)).json();
    assert(snapshot.summary && !snapshot.summary_error);
    await page.locator(`.observer-nav [data-view="agent"][data-view-id="${leader.id}"]`).click();
    await page.locator(".read-only").waitFor();
    assert.equal(await page.locator("#message-form").count(), 0);
    assert.deepEqual(errors, []);
    console.log("Real offline service UI passed: reusable roles, saved versions, one-slot three-level delegation, scoped supplemental input, finite room discussion, auxiliary call, manual DSH-mock summary and completion.");
  } finally { await browser.close(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
